# Generated by Django 6.0.5 on 2026-06-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_upi_id', models.CharField(default='admin@upi', help_text='Admin UPI ID shown to users during recharge', max_length=150)),
                ('admin_qr_image', models.ImageField(blank=True, help_text='QR Code image shown to users during recharge', null=True, upload_to='qr_codes/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Settings',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
    ]
