# Generated by Django 6.0.5 on 2026-06-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('success', 'Success'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
    ]
