# Generated by Django 6.0.5 on 2026-06-03 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('wingo_30s', 'WinGo 30 Sec'), ('wingo_1min', 'WinGo 1 Min'), ('wingo_3min', 'WinGo 3 Min')], max_length=50, unique=True)),
                ('duration_seconds', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('result_mode', models.CharField(choices=[('manual', 'Manual (Admin Selects)'), ('auto_random', 'Auto Random'), ('smart_profit', 'Smart Profit Logic')], default='auto_random', max_length=20)),
                ('current_period', models.CharField(blank=True, max_length=20)),
                ('current_game_start', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Game Rooms',
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('bet_type', models.CharField(choices=[('color', 'Color Bet'), ('number', 'Number Bet')], max_length=10)),
                ('selection', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('winning_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='game.gameroom')),
            ],
            options={
                'verbose_name_plural': 'Bets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=20)),
                ('winning_number', models.IntegerField()),
                ('winning_color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('violet', 'Violet')], max_length=10)),
                ('total_bet_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_win_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('platform_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='game.gameroom')),
            ],
            options={
                'verbose_name_plural': 'Game Results',
                'ordering': ['-created_at'],
                'unique_together': {('room', 'period')},
            },
        ),
    ]
