# Generated by Django 6.0.5 on 2026-06-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gameroom_preset_period_gameroom_preset_winning_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='green_pct',
            field=models.IntegerField(default=45, help_text='Green % probability (auto_random mode)'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='pattern_rule',
            field=models.CharField(blank=True, choices=[], default='1', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='pattern_state',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='red_pct',
            field=models.IntegerField(default=45, help_text='Red % probability (auto_random mode)'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='violet_pct',
            field=models.IntegerField(default=10, help_text='Violet % probability (auto_random mode)'),
        ),
        migrations.AlterField(
            model_name='gameroom',
            name='result_mode',
            field=models.CharField(choices=[('manual', 'Manual (Admin Selects)'), ('auto_random', 'Auto Random (Weighted %)'), ('smart_profit', 'Least Bet Wins (Platform Profit)'), ('pattern', 'Pattern-wise (Rules 1-10)')], default='auto_random', max_length=20),
        ),
    ]
