# Generated by Django 6.0.5 on 2026-06-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gameroom_green_pct_gameroom_pattern_rule_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameresult',
            options={'ordering': ['-period'], 'verbose_name_plural': 'Game Results'},
        ),
    ]
